# Generated by Django 4.2.16 on 2024-12-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinessrelation',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userbusinessrelation',
            unique_together={('user', 'business')},
        ),
        migrations.AddIndex(
            model_name='userbusinessrelation',
            index=models.Index(fields=['user'], name='adminPanel__user_id_3895cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userbusinessrelation',
            index=models.Index(fields=['business'], name='adminPanel__busines_0ca060_idx'),
        ),
    ]
