# Generated by Django 4.2.16 on 2024-12-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_userbusinessrelation_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='images/business/qr_codes'),
        ),
        migrations.AddField(
            model_name='reward',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='images/rewards/qr_codes'),
        ),
    ]
