# Generated by Django 4.2.16 on 2024-12-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_business_qrcode_reward_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/qr_codes'),
        ),
    ]
